### ISSUE TITLE
green/red icon to show status

### ISSUE THREAD

**Issue by chrisbigelow** [cpunkswritecode/onionup#6]

**Comment by elimisteve** [comment]
@chrisbigelow @reidjs Protip: you can automatically close GitHub issues with commit messages!  If you were to include "fixes #6" in the commit message that implemented this feature, this issue would close automatically when you push to the default branch of this repo (which is often `master`).

More info: https://help.github.com/articles/closing-issues-using-keywords/ and https://github.com/blog/1386-closing-issues-via-commit-messages
